// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Actionrequest_Corpus int32

const (
	Actionrequest_UNIVERSAL Actionrequest_Corpus = 0
	Actionrequest_WEB       Actionrequest_Corpus = 1
	Actionrequest_IMAGES    Actionrequest_Corpus = 2
	Actionrequest_LOCAL     Actionrequest_Corpus = 3
	Actionrequest_NEWS      Actionrequest_Corpus = 4
	Actionrequest_PRODUCTS  Actionrequest_Corpus = 5
	Actionrequest_VIDEO     Actionrequest_Corpus = 6
)

var Actionrequest_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}

var Actionrequest_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x Actionrequest_Corpus) String() string {
	return proto.EnumName(Actionrequest_Corpus_name, int32(x))
}

func (Actionrequest_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0}
}

type Actionrequest struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Corpus               Actionrequest_Corpus `protobuf:"varint,4,opt,name=corpus,proto3,enum=example.Actionrequest_Corpus" json:"corpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Actionrequest) Reset()         { *m = Actionrequest{} }
func (m *Actionrequest) String() string { return proto.CompactTextString(m) }
func (*Actionrequest) ProtoMessage()    {}
func (*Actionrequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *Actionrequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actionrequest.Unmarshal(m, b)
}
func (m *Actionrequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actionrequest.Marshal(b, m, deterministic)
}
func (m *Actionrequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actionrequest.Merge(m, src)
}
func (m *Actionrequest) XXX_Size() int {
	return xxx_messageInfo_Actionrequest.Size(m)
}
func (m *Actionrequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Actionrequest.DiscardUnknown(m)
}

var xxx_messageInfo_Actionrequest proto.InternalMessageInfo

func (m *Actionrequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Actionrequest) GetCorpus() Actionrequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return Actionrequest_UNIVERSAL
}

type Actionresponse struct {
	Text                 string                   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Age                  int32                    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Result               []*Actionresponse_Result `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Actionresponse) Reset()         { *m = Actionresponse{} }
func (m *Actionresponse) String() string { return proto.CompactTextString(m) }
func (*Actionresponse) ProtoMessage()    {}
func (*Actionresponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *Actionresponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actionresponse.Unmarshal(m, b)
}
func (m *Actionresponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actionresponse.Marshal(b, m, deterministic)
}
func (m *Actionresponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actionresponse.Merge(m, src)
}
func (m *Actionresponse) XXX_Size() int {
	return xxx_messageInfo_Actionresponse.Size(m)
}
func (m *Actionresponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Actionresponse.DiscardUnknown(m)
}

var xxx_messageInfo_Actionresponse proto.InternalMessageInfo

func (m *Actionresponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Actionresponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Actionresponse) GetResult() []*Actionresponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type Actionresponse_Result struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets             []string `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Actionresponse_Result) Reset()         { *m = Actionresponse_Result{} }
func (m *Actionresponse_Result) String() string { return proto.CompactTextString(m) }
func (*Actionresponse_Result) ProtoMessage()    {}
func (*Actionresponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1, 0}
}

func (m *Actionresponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actionresponse_Result.Unmarshal(m, b)
}
func (m *Actionresponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actionresponse_Result.Marshal(b, m, deterministic)
}
func (m *Actionresponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actionresponse_Result.Merge(m, src)
}
func (m *Actionresponse_Result) XXX_Size() int {
	return xxx_messageInfo_Actionresponse_Result.Size(m)
}
func (m *Actionresponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Actionresponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Actionresponse_Result proto.InternalMessageInfo

func (m *Actionresponse_Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Actionresponse_Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Actionresponse_Result) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

func init() {
	proto.RegisterEnum("example.Actionrequest_Corpus", Actionrequest_Corpus_name, Actionrequest_Corpus_value)
	proto.RegisterType((*Actionrequest)(nil), "example.actionrequest")
	proto.RegisterType((*Actionresponse)(nil), "example.actionresponse")
	proto.RegisterType((*Actionresponse_Result)(nil), "example.actionresponse.Result")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0x9b, 0xe6, 0xa5, 0xc9, 0xfc, 0xff, 0x2d, 0xcb, 0x20, 0x1a, 0x0a, 0x4a, 0xc8, 0x29,
	0xa7, 0x1c, 0x2a, 0x7a, 0xf3, 0x50, 0x9b, 0x28, 0xc5, 0xd8, 0xca, 0xc6, 0xb6, 0xe0, 0x6d, 0xad,
	0x8b, 0x14, 0xd2, 0x6e, 0xcc, 0x6e, 0xa0, 0x9f, 0xcc, 0x93, 0x1f, 0x4e, 0xf2, 0xa2, 0x20, 0xd6,
	0xdb, 0xf3, 0x0c, 0xbf, 0x99, 0x67, 0x76, 0x07, 0xe0, 0x85, 0x29, 0x16, 0xe6, 0x85, 0x50, 0x02,
	0x7b, 0x7c, 0xcf, 0xb6, 0x79, 0xc6, 0xfd, 0x77, 0x0d, 0xfa, 0x6c, 0xad, 0x36, 0x62, 0x57, 0xf0,
	0xb7, 0x92, 0x4b, 0x85, 0x08, 0x86, 0xe2, 0x7b, 0xe5, 0x6a, 0x9e, 0x16, 0x38, 0xb4, 0xd6, 0x78,
	0x01, 0xd6, 0x5a, 0x14, 0x79, 0x29, 0x5d, 0xc3, 0xd3, 0x82, 0xc1, 0xe8, 0x34, 0x6c, 0xfb, 0xc3,
	0x1f, 0xbd, 0xe1, 0xa4, 0x86, 0x68, 0x0b, 0xfb, 0x4f, 0x60, 0x35, 0x15, 0xec, 0x83, 0xb3, 0x98,
	0x4d, 0x97, 0x31, 0x4d, 0xc7, 0x09, 0xe9, 0x60, 0x0f, 0xf4, 0x55, 0x7c, 0x4d, 0x34, 0x04, 0xb0,
	0xa6, 0xf7, 0xe3, 0xdb, 0x38, 0x25, 0x5d, 0x74, 0xc0, 0x4c, 0xe6, 0x93, 0x71, 0x42, 0x74, 0xb4,
	0xc1, 0x98, 0xc5, 0xab, 0x94, 0x18, 0xf8, 0x1f, 0xec, 0x07, 0x3a, 0x8f, 0x16, 0x93, 0xc7, 0x94,
	0x98, 0x15, 0xb2, 0x9c, 0x46, 0xf1, 0x9c, 0x58, 0xfe, 0x87, 0x06, 0x83, 0xaf, 0x70, 0x99, 0x8b,
	0x9d, 0xe4, 0x07, 0x37, 0x27, 0xa0, 0xb3, 0x57, 0xee, 0x76, 0x3d, 0x2d, 0x30, 0x69, 0x25, 0xf1,
	0x12, 0xac, 0x82, 0xcb, 0x32, 0x53, 0xae, 0xee, 0xe9, 0xc1, 0xbf, 0xd1, 0xd9, 0xaf, 0xb7, 0x34,
	0xe3, 0x42, 0x5a, 0x53, 0xb4, 0xa5, 0x87, 0x09, 0x58, 0x4d, 0xa5, 0x9a, 0x59, 0x16, 0x59, 0x1b,
	0x53, 0x49, 0x3c, 0x02, 0x53, 0x6d, 0x54, 0xd6, 0xe4, 0x38, 0xb4, 0x31, 0x38, 0x04, 0x5b, 0xee,
	0x36, 0x79, 0xce, 0x95, 0xac, 0xb3, 0x1c, 0xfa, 0xed, 0x47, 0x77, 0x00, 0x37, 0xa2, 0xd8, 0x32,
	0x15, 0x31, 0xc5, 0xf0, 0x0a, 0xec, 0x48, 0x34, 0x1e, 0x8f, 0x0f, 0xff, 0xed, 0xf0, 0xe4, 0x8f,
	0x3d, 0xfd, 0xce, 0xb3, 0x55, 0x1f, 0xf5, 0xfc, 0x33, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x02, 0x09,
	0x05, 0xe2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FormatDataClient is the client API for FormatData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FormatDataClient interface {
	DoFormat(ctx context.Context, in *Actionrequest, opts ...grpc.CallOption) (*Actionresponse, error)
}

type formatDataClient struct {
	cc *grpc.ClientConn
}

func NewFormatDataClient(cc *grpc.ClientConn) FormatDataClient {
	return &formatDataClient{cc}
}

func (c *formatDataClient) DoFormat(ctx context.Context, in *Actionrequest, opts ...grpc.CallOption) (*Actionresponse, error) {
	out := new(Actionresponse)
	err := c.cc.Invoke(ctx, "/example.FormatData/DoFormat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormatDataServer is the server API for FormatData service.
type FormatDataServer interface {
	DoFormat(context.Context, *Actionrequest) (*Actionresponse, error)
}

// UnimplementedFormatDataServer can be embedded to have forward compatible implementations.
type UnimplementedFormatDataServer struct {
}

func (*UnimplementedFormatDataServer) DoFormat(ctx context.Context, req *Actionrequest) (*Actionresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoFormat not implemented")
}

func RegisterFormatDataServer(s *grpc.Server, srv FormatDataServer) {
	s.RegisterService(&_FormatData_serviceDesc, srv)
}

func _FormatData_DoFormat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Actionrequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatDataServer).DoFormat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.FormatData/DoFormat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatDataServer).DoFormat(ctx, req.(*Actionrequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FormatData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.FormatData",
	HandlerType: (*FormatDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoFormat",
			Handler:    _FormatData_DoFormat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
