package controllers

import (
	"encoding/json"
	"github.com/xuchengzhi/apimonitor/Thrift"
	"log"
	"strings"
)

type ThriftController struct {
	BaseController
}

func (this *ThriftController) ActRun() {
	msg := this.GetString("app")
	ips := this.GetString("ip")
	log.Println(ips)
	res := Thrift.ActRun(msg, ips)
	this.Data["json"] = Response{200, "success", res}
	this.ServeJSON()
}

func (this *ThriftController) ADB() {
	res := Thrift.ADB()
	this.Data["json"] = Response{200, "success", res}
	this.ServeJSON()
}

func (this *ThriftController) Atx() {
	res := Thrift.Atx()
	this.Data["json"] = Response{200, "success", res}
	this.ServeJSON()
}

type AutoGenerated struct {
	Order     string  `json:"order"`
	Datetime  string  `json:"datetime"`
	Font      string  `json:"font"`
	Payprice  float64 `json:"payprice"`
	Fontprice float64 `json:"fontprice"`
	Status    string  `json:"status"`
	Platform  string  `json:"platform"`
	User      string  `json:"user"`
}

func (this *ThriftController) Order() {
	msg := this.GetString("app")
	res, err := Thrift.Order(msg)
	resstr := strings.Replace(res, "'", "\"", -1)
	if err {
		var dat []AutoGenerated
		if err := json.Unmarshal([]byte(resstr), &dat); err == nil {
		}
		this.Data["json"] = Response{200, "success", dat}
	} else {
		this.Data["json"] = Response{2001, "error", res}
	}

	this.ServeJSON()
}

func (this *ThriftController) Device() {
	res := Thrift.Device()
	this.Data["json"] = Response{200, "success", res}
	this.ServeJSON()
}

func (this *ThriftController) Dev_up() {
	res := Thrift.DevUp()
	this.Data["json"] = Response{200, "success", res}
	this.ServeJSON()
}

func (this *ThriftController) ThriftAtxServer() {
	res := Thrift.ThriftAtxServer()
	this.Data["json"] = Response{200, "success", res}
	this.ServeJSON()
}

func (this *ThriftController) ThriftAdbServer() {
	res := Thrift.ThriftAdbServer()
	this.Data["json"] = Response{200, "success", res}
	this.ServeJSON()
}

func (this *ThriftController) ThriftActServer() {
	res := Thrift.ThriftActServer()
	this.Data["json"] = Response{200, "success", res}
	this.ServeJSON()
}

func (this *ThriftController) ThriftJavaServer() {
	res := Thrift.ThriftJavaServer()
	this.Data["json"] = Response{200, "success", res}
	this.ServeJSON()
}
