[hotreload]
  suffixes = [".go"]
  ignore = []

[app]
  #app 名称
  name = "you_project_name"
  #app url
  url  = "http://localhost"
  #app 文档地址
  doc = "./apidoc"
  addr = ":80"
  #单元测试调试信息
  debug = false

  [app.logger]
    level = "INFO"
    name = "application"

#数据库驱动
[database]
    dirver = "mysql"

[mysql]
   databaseName ="scrapy"
   databaseUserName ="root"
   databasePassword ="123456"
   databaseUrl = "192.168.248.249"
   databasePort = "3306"

[mongodb]
  connect = "mongodb://root:123456@127.0.0.1:27017/admin"

[sqlite]
  connect = "/tmp/gorm.db"

#reids
[redis]
  Addr = "127.0.0.1:6379"
  Password = ""
  DB = 0

[neo4j]
    connect = "http://10.10.43.111:7474/db/data"

[test]
    #测试登陆用户名
    LoginUserName = "you_test_user_name"
    #测试用户名
    LoginName = "xuchengzhi"
    #测试用户密码
    LoginPwd = "123456"
    #测试数据库驱动
    DataBaseDriver = "sqlite3"
    #测试数据库
    DataBaseConnect = "./gorm.db"
